version: '3.8'
services:
  traefik:
    image: "traefik:v2.9"
    container_name: "notes_traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "4480:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  ui:
    container_name: "ui"
    build:
      context: ./ui
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.ui-router.entrypoints=web"
      - "traefik.http.routers.ui-router.rule=PathPrefix(`/napp`)"
      - "traefik.http.routers.ui-router.service=ui-service"
      - "traefik.http.services.ui-service.loadbalancer.server.port=3000"
